// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: grpc/api.proto

package grpc_api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MovieKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MovieKey) Reset() {
	*x = MovieKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieKey) ProtoMessage() {}

func (x *MovieKey) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieKey.ProtoReflect.Descriptor instead.
func (*MovieKey) Descriptor() ([]byte, []int) {
	return file_grpc_api_proto_rawDescGZIP(), []int{0}
}

func (x *MovieKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Movie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Movie) Reset() {
	*x = Movie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_grpc_api_proto_rawDescGZIP(), []int{1}
}

func (x *Movie) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_grpc_api_proto protoreflect.FileDescriptor

var file_grpc_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x1a, 0x0a, 0x08, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x40, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x4b, 0x65, 0x79, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_api_proto_rawDescOnce sync.Once
	file_grpc_api_proto_rawDescData = file_grpc_api_proto_rawDesc
)

func file_grpc_api_proto_rawDescGZIP() []byte {
	file_grpc_api_proto_rawDescOnce.Do(func() {
		file_grpc_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_api_proto_rawDescData)
	})
	return file_grpc_api_proto_rawDescData
}

var file_grpc_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_api_proto_goTypes = []interface{}{
	(*MovieKey)(nil), // 0: grpc_api.MovieKey
	(*Movie)(nil),    // 1: grpc_api.Movie
}
var file_grpc_api_proto_depIdxs = []int32{
	0, // 0: grpc_api.serviceMovies.getMovie:input_type -> grpc_api.MovieKey
	1, // 1: grpc_api.serviceMovies.getMovie:output_type -> grpc_api.Movie
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_api_proto_init() }
func file_grpc_api_proto_init() {
	if File_grpc_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_api_proto_goTypes,
		DependencyIndexes: file_grpc_api_proto_depIdxs,
		MessageInfos:      file_grpc_api_proto_msgTypes,
	}.Build()
	File_grpc_api_proto = out.File
	file_grpc_api_proto_rawDesc = nil
	file_grpc_api_proto_goTypes = nil
	file_grpc_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceMoviesClient is the client API for ServiceMovies service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceMoviesClient interface {
	GetMovie(ctx context.Context, in *MovieKey, opts ...grpc.CallOption) (*Movie, error)
}

type serviceMoviesClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceMoviesClient(cc grpc.ClientConnInterface) ServiceMoviesClient {
	return &serviceMoviesClient{cc}
}

func (c *serviceMoviesClient) GetMovie(ctx context.Context, in *MovieKey, opts ...grpc.CallOption) (*Movie, error) {
	out := new(Movie)
	err := c.cc.Invoke(ctx, "/grpc_api.serviceMovies/getMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceMoviesServer is the server API for ServiceMovies service.
type ServiceMoviesServer interface {
	GetMovie(context.Context, *MovieKey) (*Movie, error)
}

// UnimplementedServiceMoviesServer can be embedded to have forward compatible implementations.
type UnimplementedServiceMoviesServer struct {
}

func (*UnimplementedServiceMoviesServer) GetMovie(context.Context, *MovieKey) (*Movie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}

func RegisterServiceMoviesServer(s *grpc.Server, srv ServiceMoviesServer) {
	s.RegisterService(&_ServiceMovies_serviceDesc, srv)
}

func _ServiceMovies_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceMoviesServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.serviceMovies/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceMoviesServer).GetMovie(ctx, req.(*MovieKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceMovies_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.serviceMovies",
	HandlerType: (*ServiceMoviesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMovie",
			Handler:    _ServiceMovies_GetMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/api.proto",
}
